name: run ubereats.py

on:
  workflow_dispatch:
  schedule:
    - cron: '30 * * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps firefox

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.12.1' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ubereats.requirements.txt
          
      - name: execute py script
        run: python ubereats.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "action test" --allow-empty)
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.8.0
            
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 